# Source: https://plippe.github.io/blog/2021/07/12/rust-wasm-github.html
name: Continuous integration
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cargo test --all

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cargo clippy --all -- -D warnings